//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIASA.FloodCitiSense.Mobile.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IIASA.FloodCitiSense.Mobile.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///FloodCitiSense is an early warning service for pluvial flooding that is for, but also by citizens and city authorities, and builds upon sensing technologies
        ///.
        /// </summary>
        internal static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///By using this app, you can become a valuable contributor to this service by helping to report incidents of pluvial flooding. Although still in a testing phase, future versions will include notifications from the early warning service currently being built as part of the FloodCitiSense project.
        ///.
        /// </summary>
        internal static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the terms and conditions.
        /// </summary>
        internal static string AcceptText {
            get {
                return ResourceManager.GetString("AcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advanced Info.
        /// </summary>
        internal static string AddAdvanceInfo {
            get {
                return ResourceManager.GetString("AddAdvanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If possible add a picture and/or additional information and submit!.
        /// </summary>
        internal static string AddPicturesText {
            get {
                return ResourceManager.GetString("AddPicturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already uploaded this Incident!.
        /// </summary>
        internal static string AlreadyCreated {
            get {
                return ResourceManager.GetString("AlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any signs of damage?.
        /// </summary>
        internal static string AnySignOfDamage {
            get {
                return ResourceManager.GetString("AnySignOfDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you impacted by the flood?.
        /// </summary>
        internal static string AreYouImpacted {
            get {
                return ResourceManager.GetString("AreYouImpacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small part.
        /// </summary>
        internal static string ASmallPart {
            get {
                return ResourceManager.GetString("ASmallPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile picture.
        /// </summary>
        internal static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Citys {
            get {
                return ResourceManager.GetString("Citys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City-specific recommendations.
        /// </summary>
        internal static string CitySpecificRecommendations {
            get {
                return ResourceManager.GetString("CitySpecificRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to login..
        /// </summary>
        internal static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely flooded.
        /// </summary>
        internal static string CompletelyFlooded {
            get {
                return ResourceManager.GetString("CompletelyFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Successfully.
        /// </summary>
        internal static string CreatSuccess {
            get {
                return ResourceManager.GetString("CreatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current reports.
        /// </summary>
        internal static string CurrentReport {
            get {
                return ResourceManager.GetString("CurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletingUser.
        /// </summary>
        internal static string DeletingUser {
            get {
                return ResourceManager.GetString("DeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign up..
        /// </summary>
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        internal static string Drizzle {
            get {
                return ResourceManager.GetString("Drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit / More.
        /// </summary>
        internal static string EditOrMore {
            get {
                return ResourceManager.GetString("EditOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Username.
        /// </summary>
        internal static string EmailOrUsername {
            get {
                return ResourceManager.GetString("EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing in here..
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available from the server.
        /// </summary>
        internal static string EmptyGraphMessage {
            get {
                return ResourceManager.GetString("EmptyGraphMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter later.
        /// </summary>
        internal static string EnterLater {
            get {
                return ResourceManager.GetString("EnterLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience with citizen science.
        /// </summary>
        internal static string ExperienceWithCitizenScience {
            get {
                return ResourceManager.GetString("ExperienceWithCitizenScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed!.
        /// </summary>
        internal static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter flood reports.
        /// </summary>
        internal static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Items:.
        /// </summary>
        internal static string FilterItems {
            get {
                return ResourceManager.GetString("FilterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last 3 days.
        /// </summary>
        internal static string FilterLast3Days {
            get {
                return ResourceManager.GetString("FilterLast3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last 24 hours.
        /// </summary>
        internal static string FilterLastDay {
            get {
                return ResourceManager.GetString("FilterLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last week.
        /// </summary>
        internal static string FilterLastWeek {
            get {
                return ResourceManager.GetString("FilterLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string FilterShowAll {
            get {
                return ResourceManager.GetString("FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time flood.
        /// </summary>
        internal static string FirstTimeFlood {
            get {
                return ResourceManager.GetString("FirstTimeFlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloodCitiSense.
        /// </summary>
        internal static string FloodCitiSense {
            get {
                return ResourceManager.GetString("FloodCitiSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloodCitiSense data.
        /// </summary>
        internal static string FloodCitiSenseData {
            get {
                return ResourceManager.GetString("FloodCitiSenseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall sensors.
        /// </summary>
        internal static string FloodCitiSenseRainfallSensor {
            get {
                return ResourceManager.GetString("FloodCitiSenseRainfallSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood damage.
        /// </summary>
        internal static string FloodDamage {
            get {
                return ResourceManager.GetString("FloodDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood depth.
        /// </summary>
        internal static string FloodDepth {
            get {
                return ResourceManager.GetString("FloodDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood extent.
        /// </summary>
        internal static string FloodExtent {
            get {
                return ResourceManager.GetString("FloodExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency of flood.
        /// </summary>
        internal static string FloodFrequency {
            get {
                return ResourceManager.GetString("FloodFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood occurrence.
        /// </summary>
        internal static string FloodOccurrence {
            get {
                return ResourceManager.GetString("FloodOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Report.
        /// </summary>
        internal static string FloodReport {
            get {
                return ResourceManager.GetString("FloodReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floods occasionally.
        /// </summary>
        internal static string FloodsOccasionally {
            get {
                return ResourceManager.GetString("FloodsOccasionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floods regularly.
        /// </summary>
        internal static string FloodsRegularly {
            get {
                return ResourceManager.GetString("FloodsRegularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your login details? Get help signing in..
        /// </summary>
        internal static string ForgotLogin {
            get {
                return ResourceManager.GetString("ForgotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden flooding.
        /// </summary>
        internal static string GardenFlooded {
            get {
                return ResourceManager.GetString("GardenFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden flooding.
        /// </summary>
        internal static string GardenFlooding {
            get {
                return ResourceManager.GetString("GardenFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General recommendations.
        /// </summary>
        internal static string GeneralRecommendations {
            get {
                return ResourceManager.GetString("GeneralRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting devices.
        /// </summary>
        internal static string GetAllDeviceLocation {
            get {
                return ResourceManager.GetString("GetAllDeviceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting incidents.
        /// </summary>
        internal static string GetAllIncidents {
            get {
                return ResourceManager.GetString("GetAllIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gettting local locations.
        /// </summary>
        internal static string GetAllLocalLocation {
            get {
                return ResourceManager.GetString("GetAllLocalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Location.
        /// </summary>
        internal static string GettingLocation {
            get {
                return ResourceManager.GetString("GettingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon.
        /// </summary>
        internal static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall (mm) from Sensor ID:.
        /// </summary>
        internal static string GraphTitle {
            get {
                return ResourceManager.GetString("GraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half flooded.
        /// </summary>
        internal static string HalfFlooded {
            get {
                return ResourceManager.GetString("HalfFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an account?.
        /// </summary>
        internal static string HaveAAccount {
            get {
                return ResourceManager.GetString("HaveAAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rainfall.
        /// </summary>
        internal static string HeavyRainFall {
            get {
                return ResourceManager.GetString("HeavyRainFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher than 50 cm.
        /// </summary>
        internal static string HigherThan50 {
            get {
                return ResourceManager.GetString("HigherThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House flooding.
        /// </summary>
        internal static string HouseFlooding {
            get {
                return ResourceManager.GetString("HouseFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while trying to communicate with the server. Do you want to try again?.
        /// </summary>
        internal static string HttpException {
            get {
                return ResourceManager.GetString("HttpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        internal static string IDoNotKnow {
            get {
                return ResourceManager.GetString("IDoNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload the image..
        /// </summary>
        internal static string ImageUploadFailed {
            get {
                return ResourceManager.GetString("ImageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered a rainfall type or flooding type..
        /// </summary>
        internal static string IncidentSavingWarningMessage {
            get {
                return ResourceManager.GetString("IncidentSavingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incidents found!.
        /// </summary>
        internal static string IncidentsFound {
            get {
                return ResourceManager.GetString("IncidentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Upload Error.
        /// </summary>
        internal static string IncidentUploadError {
            get {
                return ResourceManager.GetString("IncidentUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the intensity of the rain.
        /// </summary>
        internal static string IntensityText {
            get {
                return ResourceManager.GetString("IntensityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Email Address.
        /// </summary>
        internal static string InvalidUserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("InvalidUserNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        internal static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid.
        /// </summary>
        internal static string LengthNotInRange {
            get {
                return ResourceManager.GetString("LengthNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading City.
        /// </summary>
        internal static string LoadingCity {
            get {
                return ResourceManager.GetString("LoadingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadWithThreeDot {
            get {
                return ResourceManager.GetString("LoadWithThreeDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled, Please enable it and try again..
        /// </summary>
        internal static string LocationDisabled {
            get {
                return ResourceManager.GetString("LocationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Facebook.
        /// </summary>
        internal static string LogInFacebook {
            get {
                return ResourceManager.GetString("LogInFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Google.
        /// </summary>
        internal static string LogInGoogle {
            get {
                return ResourceManager.GetString("LogInGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map type.
        /// </summary>
        internal static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Intensity.
        /// </summary>
        internal static string MediumIntensity {
            get {
                return ResourceManager.GetString("MediumIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloodCitiSense.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muddy.
        /// </summary>
        internal static string Muddy {
            get {
                return ResourceManager.GetString("Muddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My feet are wet (&lt;2 cm).
        /// </summary>
        internal static string MyFeedAreWet {
            get {
                return ResourceManager.GetString("MyFeedAreWet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Settings.
        /// </summary>
        internal static string MySettings {
            get {
                return ResourceManager.GetString("MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your password.
        /// </summary>
        internal static string NewPasswordRepeat {
            get {
                return ResourceManager.GetString("NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera.
        /// </summary>
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flooding.
        /// </summary>
        internal static string NoFlooding {
            get {
                return ResourceManager.GetString("NoFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection! Do you want to enable internet and try again?.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display..
        /// </summary>
        internal static string NoItemsToDisplay {
            get {
                return ResourceManager.GetString("NoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos.
        /// </summary>
        internal static string NoPhotos {
            get {
                return ResourceManager.GetString("NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no reports saved on the phone..
        /// </summary>
        internal static string NoReportsOnPhone {
            get {
                return ResourceManager.GetString("NoReportsOnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to determine your city. Please select your city again..
        /// </summary>
        internal static string NotAbleToFindCity {
            get {
                return ResourceManager.GetString("NotAbleToFindCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the incident.
        /// </summary>
        internal static string NotAbleToSave {
            get {
                return ResourceManager.GetString("NotAbleToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to select more the current selection..
        /// </summary>
        internal static string NotAllowedToSelectAnyMore {
            get {
                return ResourceManager.GetString("NotAllowedToSelectAnyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type of flodding.
        /// </summary>
        internal static string NoTypeOfFlooding {
            get {
                return ResourceManager.GetString("NoTypeOfFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no uploaded reports..
        /// </summary>
        internal static string NoUploadedReports {
            get {
                return ResourceManager.GetString("NoUploadedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed. You need to login first..
        /// </summary>
        internal static string OperationFailedLogin {
            get {
                return ResourceManager.GetString("OperationFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Report.
        /// </summary>
        internal static string OtherReport {
            get {
                return ResourceManager.GetString("OtherReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reports.
        /// </summary>
        internal static string OtherReports {
            get {
                return ResourceManager.GetString("OtherReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park flooding.
        /// </summary>
        internal static string ParksFlooded {
            get {
                return ResourceManager.GetString("ParksFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks flooding.
        /// </summary>
        internal static string ParksFlooding {
            get {
                return ResourceManager.GetString("ParksFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset mail sent successfully.
        /// </summary>
        internal static string PasswordResetMailSentMessage {
            get {
                return ResourceManager.GetString("PasswordResetMailSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from gallery.
        /// </summary>
        internal static string PickFromGallery {
            get {
                return ResourceManager.GetString("PickFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop and review an Emergency Plan.
        /// </summary>
        internal static string Prepare1 {
            get {
                return ResourceManager.GetString("Prepare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep cash on hand to use after the flood if needed.
        /// </summary>
        internal static string Prepare10 {
            get {
                return ResourceManager.GetString("Prepare10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take all necessary steps to prevent the release of dangerous chemicals that might be stored on your property.
        /// </summary>
        internal static string Prepare11 {
            get {
                return ResourceManager.GetString("Prepare11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use plugs to prevent floodwater from backing up into sewer drains, or install flood vents or flood proof barriers.
        /// </summary>
        internal static string Prepare12 {
            get {
                return ResourceManager.GetString("Prepare12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned to local media and community messaging.
        /// </summary>
        internal static string Prepare13 {
            get {
                return ResourceManager.GetString("Prepare13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photos of key areas and critical items. Keep these on a cloud backup.
        /// </summary>
        internal static string Prepare14 {
            get {
                return ResourceManager.GetString("Prepare14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off the gas and electricity prior to leaving the property.
        /// </summary>
        internal static string Prepare15 {
            get {
                return ResourceManager.GetString("Prepare15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep updated survival and disaster recovery kits.
        /// </summary>
        internal static string Prepare2 {
            get {
                return ResourceManager.GetString("Prepare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate gas main and electrical shut-offs and anchor all fuel tanks.
        /// </summary>
        internal static string Prepare3 {
            get {
                return ResourceManager.GetString("Prepare3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If time allows, assemble and use sandbags in areas prone to flooding.
        /// </summary>
        internal static string Prepare4 {
            get {
                return ResourceManager.GetString("Prepare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your insurance broker to discuss policy, coverage and claims procedures..
        /// </summary>
        internal static string Prepare5 {
            get {
                return ResourceManager.GetString("Prepare5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish an emergency communication method (phone tree, notification system, etc.).
        /// </summary>
        internal static string Prepare6 {
            get {
                return ResourceManager.GetString("Prepare6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify a high ground meeting place.
        /// </summary>
        internal static string Prepare7 {
            get {
                return ResourceManager.GetString("Prepare7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate equipment, and valuable/perishable items off of the floor.
        /// </summary>
        internal static string Prepare8 {
            get {
                return ResourceManager.GetString("Prepare8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store all your important documents in labeled sealed plastic bags.
        /// </summary>
        internal static string Prepare9 {
            get {
                return ResourceManager.GetString("Prepare9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for flooding events and be able to respond in case of flooding.
        /// </summary>
        internal static string PrepareAndRespondText {
            get {
                return ResourceManager.GetString("PrepareAndRespondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare.
        /// </summary>
        internal static string Preparedness {
            get {
                return ResourceManager.GetString("Preparedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div dir=&quot;ltr&quot; style=&quot;text-align: left;&quot; trbidi=&quot;on&quot;&gt;
        ///&lt;div style=&quot;direction: ltr; margin-bottom: 0pt; margin-left: 0in; margin-top: 0pt; unicode-bidi: embed; word-break: normal;&quot;&gt;
        ///&lt;span style=&quot;font-family: &amp;quot;calibri&amp;quot;; font-size: 18pt;&quot;&gt;The following guidelines will help you be
        ///prepared for a flooding event:&lt;/span&gt;&lt;/div&gt;
        ///&lt;div style=&quot;direction: ltr; margin-bottom: 0pt; margin-left: 0in; margin-top: 0pt; unicode-bidi: embed; word-break: normal;&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;div style=&quot;direction: ltr; language: en-U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrepareText {
            get {
                return ResourceManager.GetString("PrepareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=unicode&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 15 (filtered)&quot;&gt;
        ///&lt;title&gt;Privacy Policy for FloodCitiSense&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:Wingdings;
        ///	panose-1:5 0 0 0 0 0 0 0 0 0;}
        ///@font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{font-family:&quot;Segoe UI&quot;;
        ///	panose-1:2 11 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyText {
            get {
                return ResourceManager.GetString("PrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to privacy policy.
        /// </summary>
        internal static string PrivacyWelcome {
            get {
                return ResourceManager.GetString("PrivacyWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem verifying your account. Please login again..
        /// </summary>
        internal static string ProblemVerifyingUserLoginAgain {
            get {
                return ResourceManager.GetString("ProblemVerifyingUserLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall (mm).
        /// </summary>
        internal static string RainfallGraph {
            get {
                return ResourceManager.GetString("RainfallGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random flood.
        /// </summary>
        internal static string RandomFlood {
            get {
                return ResourceManager.GetString("RandomFlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Error!.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was Successful.
        /// </summary>
        internal static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report floods easily and know info about other floods in parts of your city.
        /// </summary>
        internal static string ReportAndValidateText {
            get {
                return ResourceManager.GetString("ReportAndValidateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an incident.
        /// </summary>
        internal static string ReportAnIncident {
            get {
                return ResourceManager.GetString("ReportAnIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports to be uploaded.
        /// </summary>
        internal static string ReportsToBeUploaded {
            get {
                return ResourceManager.GetString("ReportsToBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is timed out. Do you want to try again?.
        /// </summary>
        internal static string RequestTimedOut {
            get {
                return ResourceManager.GetString("RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        internal static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal safety is paramount. Stay tuned to local media and evacuate when required.
        /// </summary>
        internal static string Respond1 {
            get {
                return ResourceManager.GetString("Respond1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect foundations for cracks and other significant damage, paying particular attention to retaining walls. Take pictures of all damage.
        /// </summary>
        internal static string Respond10 {
            get {
                return ResourceManager.GetString("Respond10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin cleanup as soon as possible to prevent further damage to the property and to reduce opportunities for mosquitoes and other problems from standing water.
        /// </summary>
        internal static string Respond11 {
            get {
                return ResourceManager.GetString("Respond11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordon off damaged areas until a determination is made regarding safety.
        /// </summary>
        internal static string Respond12 {
            get {
                return ResourceManager.GetString("Respond12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and disinfect everything that got wet. Mud left from floodwater can contain sewage and chemicals.
        /// </summary>
        internal static string Respond13 {
            get {
                return ResourceManager.GetString("Respond13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact insurance broker to verbally report damage so that an adjuster can be sent to the site.
        /// </summary>
        internal static string Respond14 {
            get {
                return ResourceManager.GetString("Respond14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind people around you to take cell phones and chargers and emergency kits with them when they evacuate.
        /// </summary>
        internal static string Respond2 {
            get {
                return ResourceManager.GetString("Respond2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen to media reports to learn whether the community’s water supply is safe to drink.
        /// </summary>
        internal static string Respond3 {
            get {
                return ResourceManager.GetString("Respond3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid floodwaters; water may be contaminated by oil, gasoline or raw sewage.
        /// </summary>
        internal static string Respond4 {
            get {
                return ResourceManager.GetString("Respond4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful! Water may also be electrically charged from underground or downed power lines.
        /// </summary>
        internal static string Respond5 {
            get {
                return ResourceManager.GetString("Respond5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware of areas where floodwaters have receded. Roads may have weakened and could collapse under the weight of a car.
        /// </summary>
        internal static string Respond6 {
            get {
                return ResourceManager.GetString("Respond6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement damage assessment processes. To help ensure safety, assessment activities should only be performed in teams.
        /// </summary>
        internal static string Respond7 {
            get {
                return ResourceManager.GetString("Respond7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use flashlights to examine walls, floors, doors and windows to ensure building is not in danger of collapsing. Listen for leaking gas lines.
        /// </summary>
        internal static string Respond8 {
            get {
                return ResourceManager.GetString("Respond8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure electricity is turned off prior to initiating assessment activities.
        /// </summary>
        internal static string Respond9 {
            get {
                return ResourceManager.GetString("Respond9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div dir=&quot;ltr&quot; style=&quot;text-align: left;&quot; trbidi=&quot;on&quot;&gt;
        ///&lt;div style=&quot;direction: ltr; margin-bottom: 0pt; margin-left: 0in; margin-top: 0pt; unicode-bidi: embed; word-break: normal;&quot;&gt;
        ///&lt;div style=&quot;direction: ltr; margin-bottom: 0pt; margin-left: 0.31in; margin-top: 0pt; text-indent: -0.31in; unicode-bidi: embed; word-break: normal;&quot;&gt;
        ///&lt;span style=&quot;font-size: 18.0pt;&quot;&gt;&lt;span style=&quot;font-family: Arial; mso-special-format: bullet;&quot;&gt;•&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-family: Calibri; font-size: 18pt;&quot;&gt;Personal
        ///safet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RespondText {
            get {
                return ResourceManager.GetString("RespondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River levels rising.
        /// </summary>
        internal static string RiverFlooded {
            get {
                return ResourceManager.GetString("RiverFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River flooding.
        /// </summary>
        internal static string RiverFlooding {
            get {
                return ResourceManager.GetString("RiverFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River level rising.
        /// </summary>
        internal static string RiverLevelRising {
            get {
                return ResourceManager.GetString("RiverLevelRising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample alerts.
        /// </summary>
        internal static string SampleAlerts {
            get {
                return ResourceManager.GetString("SampleAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Notification.
        /// </summary>
        internal static string SampleNotification {
            get {
                return ResourceManager.GetString("SampleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite imagery.
        /// </summary>
        internal static string SatelliteImagery {
            get {
                return ResourceManager.GetString("SatelliteImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on Phone.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and upload.
        /// </summary>
        internal static string SaveAndUpload {
            get {
                return ResourceManager.GetString("SaveAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Incident.
        /// </summary>
        internal static string SavingIncident {
            get {
                return ResourceManager.GetString("SavingIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a City.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a city to proceed..
        /// </summary>
        internal static string SelectCityToProceed {
            get {
                return ResourceManager.GetString("SelectCityToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of rain.
        /// </summary>
        internal static string SelectTheTypeOfRain {
            get {
                return ResourceManager.GetString("SelectTheTypeOfRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of flooding.
        /// </summary>
        internal static string SelectTypeOfFlooding {
            get {
                return ResourceManager.GetString("SelectTypeOfFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset link will be sent to your email to reset your password. If you don&apos;t get an email within a few minutes, please re-try..
        /// </summary>
        internal static string SendPasswordResetLinkInformation {
            get {
                return ResourceManager.GetString("SendPasswordResetLinkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor ID.
        /// </summary>
        internal static string SensorID {
            get {
                return ResourceManager.GetString("SensorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewage.
        /// </summary>
        internal static string Sewage {
            get {
                return ResourceManager.GetString("Sewage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewer blocked.
        /// </summary>
        internal static string SewerBlocked {
            get {
                return ResourceManager.GetString("SewerBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 7 days from.
        /// </summary>
        internal static string Show7DaysFrom {
            get {
                return ResourceManager.GetString("Show7DaysFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Info.
        /// </summary>
        internal static string ShowAdvancedInfo {
            get {
                return ResourceManager.GetString("ShowAdvancedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show from.
        /// </summary>
        internal static string ShowFrom {
            get {
                return ResourceManager.GetString("ShowFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last day.
        /// </summary>
        internal static string Showlastday {
            get {
                return ResourceManager.GetString("Showlastday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last week.
        /// </summary>
        internal static string Showlastweek {
            get {
                return ResourceManager.GetString("Showlastweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Photographs.
        /// </summary>
        internal static string ShowPhotographs {
            get {
                return ResourceManager.GetString("ShowPhotographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show yesterday.
        /// </summary>
        internal static string ShowYesterday {
            get {
                return ResourceManager.GetString("ShowYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any signs of obstruction?.
        /// </summary>
        internal static string SignOfObstruction {
            get {
                return ResourceManager.GetString("SignOfObstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any signs of obstruction?.
        /// </summary>
        internal static string SignOfObstructions {
            get {
                return ResourceManager.GetString("SignOfObstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birmingham Community Alert is a hi-tech messaging service for all residents and businesses in Birmingham providing emergency texts or voicemail messages during an emergency incident..
        /// </summary>
        internal static string SignUpAlertText {
            get {
                return ResourceManager.GetString("SignUpAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for alerts.
        /// </summary>
        internal static string SignUpForAlerts {
            get {
                return ResourceManager.GetString("SignUpForAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up here.
        /// </summary>
        internal static string SignUpHere {
            get {
                return ResourceManager.GetString("SignUpHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some.
        /// </summary>
        internal static string Some {
            get {
                return ResourceManager.GetString("Some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status and editing of your reports.
        /// </summary>
        internal static string StatusAndEditingOfYourReports {
            get {
                return ResourceManager.GetString("StatusAndEditingOfYourReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of reports.
        /// </summary>
        internal static string StatusOfReports {
            get {
                return ResourceManager.GetString("StatusOfReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street flooding.
        /// </summary>
        internal static string StreetFlooding {
            get {
                return ResourceManager.GetString("StreetFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted..
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Video.
        /// </summary>
        internal static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container&quot;&gt;&lt;div class=&quot;left-div-headline&quot;&gt;&lt;p class=&quot;paragraph-large&quot;&gt;Thank you for your willingness to contribute to FloodCitiSense. This document aims to provide you with adequate information on the data we receive from you, how we process it, and what we make available to the public in order to comply with the requirements of the EU General Data Protection Regulation (GDPR).&lt;/p&gt;&lt;div class=&quot;seprator-div-wrapper&quot;&gt;&lt;div data-ix=&quot;move-up&quot; class=&quot;separator&quot; style=&quot;opacity: 1; transform: translateX(0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsText {
            get {
                return ResourceManager.GetString("TermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to FloodCitiSense!.
        /// </summary>
        internal static string TermsWelcome {
            get {
                return ResourceManager.GetString("TermsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test translation.
        /// </summary>
        internal static string TestTranslation {
            get {
                return ResourceManager.GetString("TestTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some new translation.
        /// </summary>
        internal static string TestTranslation2 {
            get {
                return ResourceManager.GetString("TestTranslation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrential.
        /// </summary>
        internal static string Torrential {
            get {
                return ResourceManager.GetString("Torrential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport alerts.
        /// </summary>
        internal static string TransportAlerts {
            get {
                return ResourceManager.GetString("TransportAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of flooding.
        /// </summary>
        internal static string TypeOfFlooding {
            get {
                return ResourceManager.GetString("TypeOfFlooding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report the type of flood you are observing.
        /// </summary>
        internal static string TypeOfFloodText {
            get {
                return ResourceManager.GetString("TypeOfFloodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of rain.
        /// </summary>
        internal static string TypeOfRain {
            get {
                return ResourceManager.GetString("TypeOfRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of space flooded.
        /// </summary>
        internal static string TypeOfSpaceFlooded {
            get {
                return ResourceManager.GetString("TypeOfSpaceFlooded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is under construction right now..
        /// </summary>
        internal static string UnderConstructionTitle {
            get {
                return ResourceManager.GetString("UnderConstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Do you want to try again?.
        /// </summary>
        internal static string UnhandledWebRequestException {
            get {
                return ResourceManager.GetString("UnhandledWebRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload All.
        /// </summary>
        internal static string UploadAll {
            get {
                return ResourceManager.GetString("UploadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded reports.
        /// </summary>
        internal static string UploadedReport {
            get {
                return ResourceManager.GetString("UploadedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded successfully!.
        /// </summary>
        internal static string UploadedSuccessfully {
            get {
                return ResourceManager.GetString("UploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to upload the incident..
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading incident.
        /// </summary>
        internal static string UploadingIncident {
            get {
                return ResourceManager.GetString("UploadingIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading pictures....
        /// </summary>
        internal static string UploadingPicture {
            get {
                return ResourceManager.GetString("UploadingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your flood report has been uploaded successfully!.
        /// </summary>
        internal static string UploadMessage1 {
            get {
                return ResourceManager.GetString("UploadMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that these reports are not used in real-time or for flood response. Instead they will contribute valuable information in post-flood analysis. If you are in an emergency situation, please call the emergency services..
        /// </summary>
        internal static string UploadMessage2 {
            get {
                return ResourceManager.GetString("UploadMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contributing to FloodCitiSense!.
        /// </summary>
        internal static string UploadMessage3 {
            get {
                return ResourceManager.GetString("UploadMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to my ankles (&lt;10 cm).
        /// </summary>
        internal static string UpToMyAnkles {
            get {
                return ResourceManager.GetString("UpToMyAnkles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to my knees (&lt;50 cm).
        /// </summary>
        internal static string UpToMyKnees {
            get {
                return ResourceManager.GetString("UpToMyKnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to my shins (&lt;25 cm).
        /// </summary>
        internal static string UpToMyShins {
            get {
                return ResourceManager.GetString("UpToMyShins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User EmailI Not Confirmed.
        /// </summary>
        internal static string UserEmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account is locked. Please try login after sometime..
        /// </summary>
        internal static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate reports.
        /// </summary>
        internal static string ValidateReports {
            get {
                return ResourceManager.GetString("ValidateReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View map.
        /// </summary>
        internal static string ViewMap {
            get {
                return ResourceManager.GetString("ViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize reports and sensor information on the map view.
        /// </summary>
        internal static string VisualizeText {
            get {
                return ResourceManager.GetString("VisualizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkthrough.
        /// </summary>
        internal static string Walkthrough {
            get {
                return ResourceManager.GetString("Walkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water clarity.
        /// </summary>
        internal static string WaterClarity {
            get {
                return ResourceManager.GetString("WaterClarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecasts.
        /// </summary>
        internal static string WeatherForecasts {
            get {
                return ResourceManager.GetString("WeatherForecasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check current weather forecasts.
        /// </summary>
        internal static string WeatherText {
            get {
                return ResourceManager.GetString("WeatherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support your community by reporting floods in your area.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete!.
        /// </summary>
        internal static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Report.
        /// </summary>
        internal static string YourReport {
            get {
                return ResourceManager.GetString("YourReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reports.
        /// </summary>
        internal static string YourReports {
            get {
                return ResourceManager.GetString("YourReports", resourceCulture);
            }
        }
    }
}
